Use GitHub Actions for  builds (#532)
* Add job for testing
* Skip pre-commit build for non-default python versions
* Test via GHA
* Break up jobs
* Coverage
* Coveralls
* Coveralls tokens

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,12 +16,47 @@ jobs:
   prepare-base:
     name: Prepare base dependencies
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [3.7, 3.8]
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        id: python
+        uses: actions/setup-python@v2.1.4
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}
+          restore-keys: |
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-
+      - name: Create Python virtual environment
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          python -m venv venv
+          . venv/bin/activate
+          pip install -U pip setuptools pre-commit
+          pip install -r requirements_test.txt
+          pip install -e .
+
+  pre-commit:
+    name: Prepare pre-commit environment
+    runs-on: ubuntu-latest
+    needs: prepare-base
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
       - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-        id: python
         uses: actions/setup-python@v2.1.4
+        id: python
         with:
           python-version: ${{ env.DEFAULT_PYTHON }}
       - name: Restore base Python virtual environment
@@ -33,14 +68,11 @@ jobs:
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
             steps.python.outputs.python-version }}-${{
             hashFiles('requirements_test.txt') }}
-          restore-keys: |
-            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-{{ hashFiles('requirements_test.txt') }}
-      - name: Create Python virtual environment
+      - name: Fail job if Python cache restore failed
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
-          python -m venv venv
-          . venv/bin/activate
-          pip install -U pip setuptools pre-commit
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       - name: Restore pre-commit environment from cache
         id: cache-precommit
         uses: actions/cache@v2
@@ -59,7 +91,7 @@ jobs:
   lint-black:
     name: Check black
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -102,7 +134,7 @@ jobs:
   lint-flake8:
     name: Check flake8
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -148,7 +180,7 @@ jobs:
   lint-isort:
     name: Check isort
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -187,3 +219,112 @@ jobs:
         run: |
           . venv/bin/activate
           pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure
+
+  pytest:
+    runs-on: ubuntu-latest
+    needs: prepare-base
+    strategy:
+      matrix:
+        python-version: [3.7, 3.8]
+    name: >-
+      Run tests Python ${{ matrix.python-version }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2.1.4
+        id: python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Register Python problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/python.json"
+      - name: Install Pytest Annotation plugin
+        run: |
+          . venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures
+      - name: Run pytest
+        run: |
+          . venv/bin/activate
+          pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            --cov zigpy \
+            -o console_output_style=count \
+            -p no:sugar \
+            tests
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v2.2.0
+        with:
+          name: coverage-${{ matrix.python-version }}
+          path: .coverage
+      - name: Coveralls
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
+          COVERALLS_PARALLEL: true
+        run: |
+          . venv/bin/activate
+          coveralls
+
+
+  coverage:
+    name: Process test coverage
+    runs-on: ubuntu-latest
+    needs: pytest
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2.1.4
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Download all coverage artifacts
+        uses: actions/download-artifact@v2
+      - name: Combine coverage results
+        run: |
+          . venv/bin/activate
+          coverage combine coverage*/.coverage*
+          coverage report --fail-under=99
+          coverage xml
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v1.0.14
+      - name: Upload coverage to Coveralls
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          . venv/bin/activate
+          coveralls --finish
