Add job for testing

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -16,14 +16,17 @@ jobs:
   prepare-base:
     name: Prepare base dependencies
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: [3.7, 3.8]
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
-      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+      - name: Set up Python ${{ matrix.python-version }}
         id: python
         uses: actions/setup-python@v2.1.4
         with:
-          python-version: ${{ env.DEFAULT_PYTHON }}
+          python-version: ${{ matrix.python-version }}
       - name: Restore base Python virtual environment
         id: cache-venv
         uses: actions/cache@v2
@@ -34,13 +37,15 @@ jobs:
             steps.python.outputs.python-version }}-${{
             hashFiles('requirements_test.txt') }}
           restore-keys: |
-            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-{{ hashFiles('requirements_test.txt') }}
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-
       - name: Create Python virtual environment
         if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
           python -m venv venv
           . venv/bin/activate
           pip install -U pip setuptools pre-commit
+          pip install -r requirements_test.txt
+          pip install -e .
       - name: Restore pre-commit environment from cache
         id: cache-precommit
         uses: actions/cache@v2
@@ -51,7 +56,7 @@ jobs:
           restore-keys: |
             ${{ env.CACHE_VERSION}}-${{ runner.os }}-pre-commit-
       - name: Install pre-commit dependencies
-        if: steps.cache-precommit.outputs.cache-hit != 'true'
+        if: steps.cache-precommit.outputs.cache-hit != 'true' && ${{ matrix.python-version }} == ${{ env.DEFAULT_PYTHON}}
         run: |
           . venv/bin/activate
           pre-commit install-hooks
@@ -187,3 +192,62 @@ jobs:
         run: |
           . venv/bin/activate
           pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure
+
+  pytest:
+    runs-on: ubuntu-latest
+    needs: prepare-base
+    strategy:
+      matrix:
+        python-version: [3.7, 3.8]
+    name: >-
+      Run tests Python ${{ matrix.python-version }}
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2.1.4
+        id: python
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
+        run: |
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
+      - name: Register Python problem matcher
+        run: |
+          echo "::add-matcher::.github/workflows/matchers/python.json"
+      - name: Install Pytest Annotation plugin
+        run: |
+          . venv/bin/activate
+          # Ideally this should be part of our dependencies
+          # However this plugin is fairly new and doesn't run correctly
+          # on a non-GitHub environment.
+          pip install pytest-github-actions-annotate-failures
+      - name: Run pytest
+        run: |
+          . venv/bin/activate
+          pytest \
+            -qq \
+            --timeout=9 \
+            --durations=10 \
+            -n auto \
+            --dist=loadfile \
+            --cov zigpy \
+            -o console_output_style=count \
+            -p no:sugar \
+            tests
+      - name: Upload coverage artifact
+        uses: actions/upload-artifact@v2.2.0
+        with:
+          name: coverage-${{ matrix.python-version }}
+          path: .coverage
