Break up jobs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,11 +46,33 @@ jobs:
           pip install -U pip setuptools pre-commit
           pip install -r requirements_test.txt
           pip install -e .
-      - name: Build pre-commit environment only for ${{ env.DEFAULT_PYTHON }}
-        if: steps.python.outputs.python-version != ${{ env.DEFAULT_PYTHON }}
+
+  pre-commit:
+    name: Prepare pre-commit environment
+    runs-on: ubuntu-latest
+    needs: prepare-base
+    steps:
+      - name: Check out code from GitHub
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+        uses: actions/setup-python@v2.1.4
+        id: python
+        with:
+          python-version: ${{ env.DEFAULT_PYTHON }}
+      - name: Restore base Python virtual environment
+        id: cache-venv
+        uses: actions/cache@v2
+        with:
+          path: venv
+          key: >-
+            ${{ env.CACHE_VERSION}}-${{ runner.os }}-base-venv-${{
+            steps.python.outputs.python-version }}-${{
+            hashFiles('requirements_test.txt') }}
+      - name: Fail job if Python cache restore failed
+        if: steps.cache-venv.outputs.cache-hit != 'true'
         run: |
-          echo "Skipping pre-commit build"
-          exit 0
+          echo "Failed to restore Python virtual environment from cache"
+          exit 1
       - name: Restore pre-commit environment from cache
         id: cache-precommit
         uses: actions/cache@v2
@@ -69,7 +91,7 @@ jobs:
   lint-black:
     name: Check black
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -112,7 +134,7 @@ jobs:
   lint-flake8:
     name: Check flake8
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
@@ -158,7 +180,7 @@ jobs:
   lint-isort:
     name: Check isort
     runs-on: ubuntu-latest
-    needs: prepare-base
+    needs: pre-commit
     steps:
       - name: Check out code from GitHub
         uses: actions/checkout@v2
